spring:
  application:
    name: teste-pratico
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/${MYSQL_DB:deliverit}?useTimezone=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:    hibernate:      ddl-auto: update