CREATE TABLE payment_account(
	ID int NOT NULL,
	NAME varchar(255) NOT NULL,
    VALUE_ORIGINAL DECIMAL(10,2) NOT NULL,
    VALUE_ADJUSTED DECIMAL(10,2) NOT NULL,
    DAYS_OF_DELAY int NOT NULL,
    PAYMENT_DATE date NOT NULL,
    PRIMARY KEY (ID)
);